#include QMK_KEYBOARD_H

/* the izumi keymap
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_3x6_3(LT(6, KC_NO), KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, LT(6, KC_NO), KC_TAB, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, OSL(4), KC_CAPS, LCTL_T(KC_Z), LALT_T(KC_X), KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, RALT_T(KC_DOT), RCTL_T(KC_SLSH), TG(7), OSM(MOD_LSFT), LT(2, KC_BSPC), LT(3, KC_ESC), KC_ENT, LT(5, KC_SPC), RGUI_T(KC_DEL)),
                                                              [1] = LAYOUT_split_3x6_3(LT(6, KC_NO), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LT(6, KC_NO), KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_QUOT, OSL(4), KC_ESC, LCTL_T(KC_Z), LALT_T(KC_X), KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, RALT_T(KC_DOT), RCTL_T(KC_SLSH), TG(7), OSM(MOD_LSFT), LT(2, KC_BSPC), LT(3, KC_ESC), KC_ENT, LT(5, KC_SPC), RGUI_T(KC_DEL)),
                                                              [2] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ASTR, KC_7, KC_8, KC_9, KC_SLSH, KC_NO, KC_NO, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO, KC_PLUS, KC_4, KC_5, KC_6, KC_EQL, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DLR, KC_1, KC_2, KC_3, KC_PERC, KC_NO, KC_NO, KC_NO, KC_NO, KC_MINS, KC_SPC, KC_DOT),
                                                              [3] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LT, KC_LBRC, KC_RBRC, KC_GT, KC_NO, KC_NO, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO, KC_PLUS, KC_COLN, KC_LPRN, KC_RPRN, KC_SCLN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DQUO, KC_AMPR, KC_PIPE, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_UNDS, KC_SPC, KC_GRV),
                                                              [4] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, SGUI(KC_3), SGUI(KC_4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_INT2, LCTL(KC_SPC), C(G(KC_SPC)), KC_CAPS, KC_NO, KC_NO, LGUI(KC_SPC), KC_S, KC_N, KC_T, KC_NO, KC_NO, CG_NORM, CG_SWAP, DF(1), DF(0), KC_NO, KC_NO, KC_T, KC_T, KC_M, KC_M, KC_NO, KC_MUTE, KC_MPLY, KC_MNXT, KC_NO, KC_NO, KC_NO),
                                                              [5] = LAYOUT_split_3x6_3(KC_NO, LGUI(KC_GRV), LGUI(KC_TAB), KC_HOME, KC_END, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LGUI(KC_LBRC), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, LGUI(KC_RBRC), KC_NO, KC_RSFT, KC_RGUI, KC_RALT, KC_RCTL, KC_NO, KC_NO, KC_UNDO, KC_CUT, KC_COPY, KC_PSTE, KC_NO, KC_NO, KC_WH_D, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_TAB, KC_BSPC, KC_ESC, KC_NO, KC_NO, KC_NO),
                                                              [6] = LAYOUT_split_3x6_3(KC_NO, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11, KC_F12, KC_NO, BL_DEC, KC_BRID, KC_BRIU, BL_INC, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_NO, KC_NO, KC_MUTE, KC_MPLY, KC_MSTP, KC_NO, KC_NO, KC_F10),
                                                              [7] = LAYOUT_split_3x6_3(KC_1, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_3, KC_WH_D, KC_MS_U, KC_WH_U, KC_6, KC_7, KC_2, KC_A, KC_S, KC_D, KC_F, KC_G, KC_4, KC_MS_L, KC_MS_D, KC_MS_R, KC_8, KC_9, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_5, KC_WH_L, KC_BTN3, KC_WH_R, KC_0, KC_TRNS, KC_LCTL, KC_SPC, KC_LGUI, KC_ENT, KC_BTN1, KC_BTN2)};

#ifdef OLED_ENABLE
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    // make corne screen upright
    return OLED_ROTATION_270;
}

#    define L_BASE 0
#    define L_QWERTY 1
#    define L_NUM 2
#    define L_CODE 3
#    define L_ONESHOT 4
#    define L_NAV 5
#    define L_SYS 6
#    define L_FPS 7

void oled_render_layer_state(void) {
    oled_write_ln_P(PSTR("Izumi\nv5.1\n\n"), false);
    oled_write_ln_P(PSTR("Layer"), false);
    switch (layer_state) {
        case L_BASE:
            oled_write_ln_P(PSTR("CLMK"), false);
            break;
        case L_QWERTY:
            oled_write_ln_P(PSTR("QWTY"), false);
            break;
        case L_NUM:
            oled_write_ln_P(PSTR("NUM"), false);
            break;
        case L_CODE:
            oled_write_ln_P(PSTR("CODE"), false);
            break;
        case L_ONESHOT:
            oled_write_ln_P(PSTR("1SHOT"), false);
            break;
        case L_NAV:
            oled_write_ln_P(PSTR("NAV"), false);
            break;
        case L_SYS:
            oled_write_ln_P(PSTR("SYS"), false);
            break;
        case L_FPS:
            oled_write_ln_P(PSTR("FPS"), false);
            break;
    }
    oled_write_ln_P(PSTR("\n"), false);
}

char keylog_str[24] = {};

const char code_to_name_caps[60] = {' ', ' ', ' ', ' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'R', 'E', 'B', 'T', '_', '-', '=', '[', ']', '\\', '#', ';', '\'', '`', ',', '.', '/', ' ', ' ', ' '};

void set_keylog(uint16_t keycode, keyrecord_t* record) {
    char name = ' ';
    if (keycode < 60) {
        name = code_to_name_caps[keycode];
    }

    // update keylog
    snprintf(keylog_str, sizeof(keylog_str), "%c", name);
}

void oled_render_keylog(void) {
    oled_write(keylog_str, false);
}

void render_bootmagic_status(bool status) {
    // Show Ctrl-Gui Swap options
    static const char PROGMEM logo[][2][3] = {
        {{0x97, 0x98, 0}, {0xb7, 0xb8, 0}},
        {{0x95, 0x96, 0}, {0xb5, 0xb6, 0}},
    };
    if (status) {
        oled_write_ln_P(logo[0][0], false);
        oled_write_ln_P(logo[0][1], false);
    } else {
        oled_write_ln_P(logo[1][0], false);
        oled_write_ln_P(logo[1][1], false);
    }
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        oled_render_layer_state();
        oled_render_keylog();
    } else {
        // fix my slave being off someday
    }

    return false;
}

bool process_record_user(uint16_t keycode, keyrecord_t* record) {
    if (record->event.pressed) {
        set_keylog(keycode, record);
    }

    return true;
}
#endif // OLED_ENABLE
